// ── EMOJI PICKER DATA (AUDIT #5) ─────────────────────────────────
// ~600 emoji with search keywords, split from app.js. Duplicate keys
// from the hand-authored era are merged here (JS object literals
// silently keep the last duplicate, which made earlier keyword sets
// unsearchable). Keys must stay unique - the build warns otherwise.

export const EP_DATA = {
  // ── Packs & Containers
  '🎒':'backpack pack bag daypack hiking gear', '🧳':'luggage suitcase travel bag',
  '👜':'bag purse handbag', '👝':'pouch clutch bag small',
  '🎽':'vest running sports shirt gym', '📦':'box package container item gear',
  '🗃️':'card box file organize storage', '🪣':'bucket pail water container',
  '🫙':'jar container preserve bottle store pickle', '🧴':'bottle lotion sunscreen liquid soap',
  '🫗':'flask pour liquid tilt', '🥤':'cup bottle soft flask drink straw',
  '🍶':'flask sake nalgene bottle container', '🥛':'milk bottle white drink dairy',
  '🧃':'juice box drink carton pack', '🧋':'boba bubble tea cup drink',
  '🫖':'teapot kettle hot brew drink', '☕':'coffee hot espresso energy drink',
  '🍺':'beer bottle drink cold brown', '🍷':'wine glass red drink',
  '💧':'water drop hydration liquid wet', '💦':'water splash drops sweat hydrate',
  '🚰':'faucet tap water clean sink', '⛲':'fountain water jet pump',
  // ── Outdoor & Shelter
  '⛺':'tent camping camp outdoor shelter', '🏕️':'campsite camp outdoor fire tent',
  '🛖':'hut cabin shelter camp lodge', '🏡':'house home cabin shelter',
  '🪵':'log wood fuel fire camp', '🔥':'fire flame camp hot burn fuel',
  '🕯️':'candle light flame camp dark', '🪔':'lamp oil light diya fire',
  '🔦':'flashlight torch light headlamp emergency dark', '💡':'light bulb idea lamp bright electric glow',
  '🌲':'tree pine forest evergreen camp', '🌳':'tree deciduous forest nature oak',
  '🌵':'cactus desert dry southwest prickly', '🌴':'palm tropical beach island',
  '🌿':'herb plant green nature leaf', '🍃':'leaf green wind nature blowing',
  '🍀':'clover luck green four leaf', '🌾':'wheat grass grain field straw',
  '🌻':'sunflower flower yellow summer bright', '🌹':'rose red flower bloom',
  '🍄':'mushroom fungus forest food earthy', '🌰':'chestnut nut food autumn fall roast',
  '🏔️':'mountain snow peak alpine summit climb', '⛰️':'mountain hill peak elevation',
  '🗻':'mountain fuji peak snow japan', '🌋':'volcano lava mountain erupt',
  '🏜️':'desert sand dry arid dune', '🏞️':'park landscape valley nature river',
  '🌄':'sunrise mountain dawn landscape morning', '🌅':'sunrise sunset horizon ocean',
  '🌌':'galaxy space stars milky way night', '🌠':'shooting star wish night falling',
  '🌈':'rainbow colorful arc weather sky', '⭐':'star yellow rate shine',
  '🌟':'glowing star shine sparkle bright', '💫':'dizzy star spin sparkle',
  '✨':'sparkles shine magic glitter', '☀️':'sun sunny solar summer heat bright',
  '🌤️':'mostly sunny cloud weather partly', '⛅':'partly cloudy weather cloud sun',
  '🌧️':'rain water wet storm weather cloud', '🌨️':'snow flurry blizzard winter cold',
  '🌩️':'thunderstorm lightning storm cloud', '🌪️':'tornado twister storm wind',
  '🌫️':'fog mist haze cloud weather', '❄️':'snow cold ice winter freeze flake',
  '🧊':'ice cube cold freeze water chill', '☃️':'snowman winter cold snow holiday',
  '🌊':'wave ocean sea water surf swell', '🏖️':'beach sand ocean summer sun',
  '🌁':'fog mist bridge city',
  // ── Clothing & Worn
  '🥾':'boot hiking trail outdoor shoe footwear', '👟':'sneaker running shoe sport trainer',
  '👠':'heel shoe dress formal women', '🥿':'flat shoe casual loafer',
  '🧥':'jacket coat shell rain windbreaker outdoor', '🥼':'coat lab white long',
  '👘':'kimono japanese robe traditional dress', '🧣':'scarf warm winter neck wool wrap',
  '🧤':'gloves warm hands winter climbing grip mittens', '🧢':'cap hat sun visor baseball',
  '👒':'hat sun floppy brim women summer', '🎩':'top hat formal tall black',
  '⛑️':'helmet hard safety rescue white first aid', '🪖':'helmet military safety hard hat mips',
  '🕶️':'sunglasses sun cool eye shade uv', '🥽':'goggles safety ski eye snow swim',
  '🧦':'socks feet warm wool merino hike', '👕':'shirt tshirt base layer top clothing',
  '👗':'dress clothes women formal', '👖':'pants jeans trousers clothing',
  '🩳':'shorts pants summer swim casual', '🩲':'briefs underwear base layer bottom',
  '🌡️':'thermometer temperature fever heat cold measure',
  '🦺':'vest safety reflective high vis jacket', '👔':'tie shirt formal business dress',
  // ── Sport & Activity
  '🚵':'mountain bike mtb cycling trail sport', '🚴':'cycling bike road sport pedal',
  '🏃':'running run jog sprint trail race', '🏋️':'weightlifting gym strong barbell fitness',
  '🧗':'climbing rock boulder ascent sport crag', '🤸':'gymnastics cartwheel acrobatics flex',
  '🏊':'swimming swim pool water sport freestyle', '🤽':'water polo swim pool sport',
  '🏄':'surfing surf wave beach board sport', '🛶':'canoe kayak paddle river water',
  '🚣':'rowing boat oar water crew sport', '🤿':'scuba dive snorkel underwater mask',
  '⛷️':'skiing ski snow alpine downhill winter', '🏂':'snowboarding snow sport winter jump',
  '🛷':'sled toboggan snow winter slide', '🎿':'ski slope snow sport winter',
  '🏇':'horse racing jockey equestrian sport ride', '🤺':'fencing sword épée sport',
  '🥊':'boxing glove fight punch sport', '🥋':'martial arts karate judo fight',
  '🎣':'fishing fish rod catch angling lake', '🏹':'bow arrow archery aim shoot sport',
  '🧘':'yoga meditation balance pose calm breath', '⛹️':'basketball dribble sport ball',
  '🤼':'wrestling grapple fight sport pair mat', '🤾':'handball throw ball sport',
  '🏌️':'golf club sport swing green putt', '🎯':'target aim bullseye archery goal',
  '🎱':'billiards pool ball eight cue game', '🛹':'skateboard skate board trick',
  '🧜':'mermaid sea swim ocean mythical', '🏆':'trophy win champion gold prize award',
  '🥇':'gold medal first champion winner sport', '🥈':'silver medal second runner up',
  '🥉':'bronze medal third place sport', '🏅':'medal sport award winner prize',
  // ── Safety & Emergency
  '🚨':'alarm siren police rescue red emergency',
  '🛟':'lifebuoy rescue safety water ring flotation', '📡':'satellite dish signal communication beacon antenna', '🛰️':'satellite gps tracker orbit beacon space track',
  '🆘':'sos help emergency rescue distress call', '☣️':'biohazard danger warning toxic chemical',
  '⚠️':'warning caution danger alert sign hazard', '🚫':'no prohibited ban forbidden stop',
  '⛔':'no entry stop prohibit traffic red', '🔴':'red circle dot stop danger alert',
  '🟡':'yellow circle dot caution warning amber', '🟢':'green circle dot go safe ok',
  '🔺':'red triangle up warning danger alert', '🪬':'nazar protection evil eye bead amulet',
  '🛡️':'shield protect defend safety armor guard', '⚔️':'swords crossed battle fight guard',
  '🏳️':'flag white surrender peace signal', '🚩':'red flag warning marker signal',
  // ── Medical & Health
  '🩺':'stethoscope doctor medical health kit check', '💊':'pill medicine tablet drug pharmacy',
  '🩹':'bandage wound first aid cut blister patch', '🩻':'xray scan bone medical injury',
  '🩼':'crutch injury broken support leg', '🩸':'blood drop medical emergency injury',
  '🧬':'dna science biology genetics medical lab', '🔬':'microscope science lab biology magnify',
  '🏥':'hospital medical emergency health clinic', '💉':'injection needle vaccine medical syringe',
  '🧪':'flask lab science chemical experiment test', '🧫':'petri dish science lab biology culture',
  '🚑':'ambulance emergency rescue medical red lights', '🧠':'brain mind think medical neuro',
  '🦷':'tooth dental oral medical health', '🦴':'bone skeleton medical anatomy',
  '👁️':'eye sight vision medical optical', '🫀':'heart cardiac organ medical anatomy',
  '🫁':'lungs breathing organ medical anatomy', '💪':'strong muscle flex fitness arm gym',
  '🤝':'handshake assist partnership help support', '🫶':'care love support heart hands',
  // ── Tools & Hardware
  '🔧':'wrench tool fix repair mechanic adjust', '🔨':'hammer tool build hit construct',
  '⛏️':'pickaxe mine dig climb tool', '🪛':'screwdriver tool fix repair tighten',
  '🪚':'saw tool cut woodwork lumber', '🔩':'bolt nut screw hardware fasten thread',
  '🗜️':'clamp tool compress fix vise grip', '⚙️':'gear cog settings mechanical tool system',
  '🪝':'hook hang clip attach carabiner catch', '🧲':'magnet attract metal stick pull',
  '🔋':'battery power charge electric energy cell', '🪫':'battery low empty dead uncharged',
  '🔌':'plug power electric connect outlet cord',
  '📎':'paperclip attach clip link fasten', '🧷':'safety pin pin sew attach fix clasp',
  '✂️':'scissors cut tool craft snip trim', '🪤':'mousetrap trap catch snap spring pest',
  '🏗️':'construction build scaffold crane structure work site', '⚒️':'hammer pick tool mining work labor',
  '🛠️':'tools repair build wrench hammer fix kit', '🧰':'toolbox tools repair kit organize',
  '🪜':'ladder climb step rungs ascend tall', '🔑':'key lock access open carabiner unlock',
  '🗝️':'key old lock access skeleton vintage', '🔐':'locked key secure padlock shut private',
  '🔒':'lock secure locked shut padlock', '🔓':'unlocked open lock access free',
  '🪓':'axe chop cut hatchet wood fell', '🗡️':'dagger knife blade cut sharp weapon',
  '🪃':'boomerang throw return sport curve', '🪄':'wand magic trick sparkle fantasy', '🔮':'crystal ball magic predict future mystic',
  // ── Navigation & Tech
  '🗺️':'map navigation explore topo route geography', '🧭':'compass navigation direction orienteering bearing',
  '📍':'pin location map place marker spot', '📌':'pushpin note location mark bulletin',
  '🌐':'globe world earth international network web', '📻':'radio communication signal listen broadcast',
  '📱':'phone mobile smartphone sos communicate gps', '💻':'laptop computer notebook device screen',
  '🖥️':'computer monitor screen desktop display', '⌚':'watch time wrist gps smart',
  '📷':'camera photo picture photography document', '📸':'camera flash photo selfie snap',
  '🎥':'movie camera film video record', '🔭':'telescope astronomy scout view observe',
  '📐':'ruler angle math geometry measure square', '📏':'ruler measure straight line length',
  '🖨️':'printer print paper output copy', '💾':'disk save storage data floppy',
  '🔍':'search magnify zoom find inspect glass', '📲':'phone download tap touch screen',
  // ── Food & Nutrition
  '🍎':'apple fruit red food snack healthy', '🍊':'orange citrus fruit food vitamin',
  '🍋':'lemon citrus yellow sour food tart', '🍇':'grapes purple fruit food wine',
  '🍓':'strawberry red berry fruit food sweet', '🫐':'blueberry berry blue fruit food antioxidant',
  '🍒':'cherry red fruit food sweet stone', '🍑':'peach fruit food soft sweet',
  '🥭':'mango tropical fruit food yellow sweet', '🍍':'pineapple tropical fruit food spiky',
  '🥥':'coconut tropical food drink milk white', '🥝':'kiwi green fruit food slice fresh',
  '🍌':'banana yellow fruit food energy potassium', '🍐':'pear green fruit food sweet',
  '🍏':'green apple fruit food healthy crisp', '🍈':'melon fruit food green sweet cantaloupe',
  '🍅':'tomato red vegetable food pizza sauce', '🫑':'pepper bell vegetable food green yellow red',
  '🥦':'broccoli green vegetable food healthy fiber', '🥕':'carrot orange vegetable food healthy beta',
  '🌽':'corn maize vegetable food yellow grain', '🥜':'peanut nut food snack protein butter',
  '🫘':'bean legume food protein fiber lentil', '🧅':'onion food cook vegetable savory',
  '🧄':'garlic food cook vegetable flavor pungent', '🥔':'potato food starch vegetable carb',
  '🍞':'bread loaf food baked wheat carb', '🥐':'croissant bread baked food french pastry',
  '🫓':'flatbread pita food baked wrap tortilla', '🥚':'egg food protein breakfast chicken',
  '🍳':'frying egg cook breakfast pan', '🧇':'waffle breakfast food grid sweet',
  '🥞':'pancake breakfast food stack syrup', '🧀':'cheese dairy food yellow melted',
  '🥩':'meat steak protein food beef grill', '🍗':'chicken poultry food protein leg',
  '🌭':'hotdog sausage food frank bun grill', '🍔':'burger food beef bun grill fast',
  '🍟':'fries potato food fast fried salty', '🥪':'sandwich food lunch bread meat deli',
  '🌮':'taco mexican food tortilla corn', '🌯':'wrap burrito food tortilla chicken',
  '🥗':'salad green healthy food vegetable bowl', '🍜':'noodle ramen soup food asian bowl',
  '🍫':'chocolate sweet candy food bar dark', '🍬':'candy sweet sugar food treat',
  '🍭':'lollipop candy sweet food swirl stick', '🍯':'honey jar sweet food golden bear',
  '🧂':'salt spice seasoning food mineral sodium', // ── Vehicles & Transport
  '🏍️':'motorcycle motorbike moto ride speed trail', '🚗':'car vehicle drive transport auto',
  '🛻':'pickup truck offroad utility vehicle rugged', '🚙':'suv car jeep offroad vehicle 4wd',
  '🏎️':'racing car fast formula speed race track', '🚓':'police car emergency law rescue',
  '🚒':'fire truck emergency rescue red fighter',
  '🚚':'truck delivery transport cargo haul', '🚛':'semi truck cargo transport hauler',
  '🚜':'tractor farm agriculture vehicle field', '🚲':'bicycle bike cycle pedal ride',
  '🛵':'scooter moped ride urban electric', '🛴':'kick scooter electric ride urban',
  '🚁':'helicopter fly air rescue hover emergency', '✈️':'airplane fly travel plane air trip',
  '🛩️':'small plane fly aircraft private', '🚀':'rocket space launch fast nasa',
  '🛳️':'ship cruise ocean sea travel boat large', '⛵':'sailboat sail wind ocean sea',
  '🚤':'speedboat fast water motor boat', '🛸':'ufo flying saucer space alien sci-fi disc',
  // ── Symbols & Misc
  '💎':'diamond gem precious valuable crystal', '💰':'money bag rich gold cash coins',
  '🎖️':'medal military honor award achievement', '🎗️':'ribbon awareness fundraiser charity',
  '🎪':'circus tent show carnival performance fun', '🎨':'art palette paint color creative',
  '🎭':'theater mask drama performance stage', '🎬':'film clapper movie video slate',
  '🎤':'microphone sing music perform vocal', '🎵':'music note song sound melody audio',
  '🎶':'music notes song melody harmony', '🎸':'guitar music rock string instrument',
  '🥁':'drum music beat rhythm percussion', '🎺':'trumpet music brass instrument jazz',
  '🎻':'violin music classical string instrument', '🎲':'dice game random chance board',
  '🎰':'slot machine casino game luck spin', '🃏':'joker card game wild deck',
  '🎮':'game controller video play console', '🧩':'puzzle piece jigsaw fit connect',
  '🧸':'teddy bear stuffed toy soft comfort', '🪆':'doll matryoshka nesting toy',
  '🪁':'slingshot toy shoot aim rubber band', '🎁':'gift present wrap surprise box',
  '🎀':'ribbon bow pink gift decoration', '🎊':'confetti party celebrate pop',
  '🎉':'party popper celebrate tada fun confetti', '🪅':'piñata celebrate candy hit fiesta',
  '🔏':'locked pen privacy signature',
  '📢':'megaphone announce loud speaker broadcast', '📣':'loudspeaker announce cheering',
  '🔔':'bell alert notify sound ring', '🔕':'mute silent no sound bell off',
  '🎼':'sheet music score compose notation',
  '🧯':'fire extinguisher safety emergency red', '🪠':'plunger tool drain fix unclog',
  '🧹':'broom sweep clean brush floor', '🧺':'basket hamper laundry carry weave',
  '🪑':'chair seat furniture sit rest', '🛏️':'bed sleep rest night hotel camp',
  '🪞':'mirror reflection glass look vanity', '🪟':'window glass look outside frame',
  '🚪':'door open close enter exit room', '🗑️':'trash bin delete garbage waste',
  '🛁':'bathtub bath soak clean water tub', '🚿':'shower wash spray clean hygiene',
  '🧼':'soap clean wash hygiene lather bar', '🪥':'toothbrush dental clean oral hygiene',
  '🧻':'toilet paper tissue roll clean wipe', '🪒':'razor shave blade cut sharp groom',
  '💈':'barber pole spin red white blue groom', '🔗':'link chain connect attach bind',
  '⛽':'fuel gas petrol fill energy station', '🚧':'construction warning road barrier orange',
  '🛤️':'railway track rail road path trail', '🛣️':'highway road freeway asphalt drive',
  };

// Category tabs reference EP_DATA keys
export const EP_TABS = [
  {label:'🎒', name:'Packs',    keys:['🎒','🧳','📦','🫙','🥤','🍶','💧','💦','🚰','🪣','🧴','🫗','🧃','🧋','☕','🍺','🍷','🥛','🫖','⛲']},
  {label:'⛺', name:'Outdoors', keys:['⛺','🏕️','🛖','🔥','🕯️','🪔','🔦','💡','🌲','🌳','🌵','🌴','🌿','🍃','🌾','🌻','🍄','🌰','🏔️','⛰️','🗻','🌋','🏜️','🏞️','🌄','🌅','🌊','🌈','☀️','⛅','🌧️','🌨️','❄️','🧊','🌌','🌠','🌪️','🌩️','🌫️','🪵']},
  {label:'🥾', name:'Worn',     keys:['🥾','👟','🧥','🧣','🧤','🧢','⛑️','🪖','🕶️','🥽','🧦','👕','👖','🩳','🩲','🦺','👔','👗','👒','🎩','🥼','👜','👝','🛡️']},
  {label:'🚵', name:'Sport',    keys:['🚵','🚴','🏃','🏋️','🧗','🤸','🏊','🏄','🛶','🚣','🤿','⛷️','🏂','🛷','🎿','🏇','🥊','🥋','🎣','🏹','🧘','⛹️','🤼','🤾','🏌️','🎯','🎱','🛹','🤺','🏆','🥇','🥈','🥉','🏅']},
  {label:'🩺', name:'Medical',  keys:['🩺','💊','🩹','🩻','🩼','🩸','🧬','🔬','🏥','💉','🧪','🧫','🚑','🧠','🦷','🦴','👁️','🫀','🫁','💪','🤝','🫶','🆘','⚠️','☣️','🛟','⛑️']},
  {label:'🔧', name:'Tools',    keys:['🔧','🔨','⛏️','🪛','🪚','🔩','🗜️','⚙️','🪝','🧲','🔋','🪫','💡','🔌','📎','🧷','✂️','🪤','🛠️','🧰','🪜','🔑','🗝️','🔐','🔒','🔓','🪓','🗡️','🪃','🪄','🏗️','⚒️','🪬','🛡️','⚔️']},
  {label:'🗺️', name:'Nav & Tech',keys:['🗺️','🧭','📍','📌','🌐','📻','📡','🛰️','📱','💻','⌚','📷','📸','🔭','📐','📏','🔍','🎥','🔮','🖥️']},
  {label:'🍎', name:'Food',     keys:['🍎','🍊','🍋','🍇','🍓','🫐','🍒','🥭','🍍','🥥','🥝','🍌','🍏','🍅','🫑','🥦','🥕','🌽','🥜','🫘','🧅','🧄','🥔','🍞','🥐','🫓','🥚','🧇','🥞','🧀','🥩','🍗','🥪','🌮','🌯','🥗','🍜','🍫','🍬','🍭','🍯','🧂','🍄','🌰','🌭','🍔','🍟']},
  {label:'🏍️', name:'Vehicles', keys:['🏍️','🚗','🛻','🚙','🏎️','🚲','🛵','🛴','🚁','✈️','🛩️','🚀','🛳️','⛵','🚤','🛶','🛸','🚜','🚚','🚛','🚑','🚒','🚓']},
  {label:'⭐', name:'Symbols',  keys:['⭐','🌟','💫','✨','💎','💰','🎖️','🎗️','🎪','🎨','🎭','🎬','🎤','🎵','🎶','🎸','🥁','🎺','🎻','🎲','🎮','🧩','🎁','🎉','🎊','📢','🔔','🧯','⛽','🚨','🚩','🔴','🟡','🟢','🔺','🔥','🌈']},
];
